### PR TITLE
IO -> Execution

### PR DESCRIPTION
**Pull request by triggerNZ**
Conversion between scalaz.effect.IO and scalding Execution

### CODE REVIEW

**Comment by vineethvarghese** [comment]
version bump?

**Comment by rowandavies** [comment]
Maybe add a ~> natural transformation?  (Not essential.)

**Comment by triggerNZ** [comment]
@rowandavies I really like the `~>` idea but think that if we are doing that we should write `~>` instances for all of the things we are converting from (not just `IO`) and have a general

```scala
def from[M[_], V](m: M[V])(implicit nat: M ~> Execution): Execution[V] = ...
```

This feels like a bit of a refactor and probably should be in a separate PR

**Comment by triggerNZ** [comment]
@vineethvarghese I bumped the version. Other than that are you happy for me to merge?

**Comment by vineethvarghese** [comment]
👍

**Pull request merged**
