### PR TITLE
Do not export compile-time macro dependencies. This commit fixes #355

### LINKED ISSUE #355: Macro dependencies are pulled in at runtime
Libraries which depend on maestro are going to pull in all maestro's dependencies at runtime. This includes macro dependencies which are only required at compile time.

Ideally there would be a reasonable way of importing maestro which allowed me to compile against all dependencies, including macro dependencies, but only include non-macro dependencies at runtime.

### PR DESCRIPTION
**Pull request by triggerNZ**

### CODE REVIEW

**Comment by kfish** [comment]
LGTM :+1:

**Comment by SamRoberts** [comment]
Do downstream projects which build against maestro get the macros on their compile time classpath, but not on their runtime path?

**Comment by triggerNZ** [comment]
After further investigation, I haven't proven that this works. It was working due to the macro dependencies being pulled in transitively from other projects.

**Comment by triggerNZ** [comment]
Closing, since we have to refactor macro dependencies in dependent projects too, which is scope beyond this PR

**Pull request closed without merging**
