### PR TITLE
Omde 272 fix field type

### PR DESCRIPTION
**Pull request by knservis**
It looks like it would be far more useful to get the actual manifest rather than it's class. This is a problem for us as we need to evaluate the manifest of a field in our application.

### CODE REVIEW

**Comment by vineethvarghese** [comment]
You don't have a version update.

**Comment by vineethvarghese** [comment]
Please squash commits and add update the version before merging :+1:

**Comment by vineethvarghese** [comment]
Please squash commits and update the version before merging :+1:

**Comment by knservis** [comment]
Awesome. Can you please tell me where to change the version.

**Comment by vineethvarghese** [comment]
In case you are not aware, please use fast forward merge.

**Comment by stephanh** [comment]
@knservis next time please don't introduce merge commits. As you can see from our past history we use fast forward merges to create a linear git history.

**Pull request merged**
