### PR TITLE
Adding a timeout for fetching job counters

### PR DESCRIPTION
**Pull request by vineethvarghese**
The timeout value is set to 60 seconds which seems sufficiently high but I am happy to change it.

### CODE REVIEW

**Comment by vineethvarghese** [comment]
Addresses https://github.com/CommBank/maestro/issues/385 for the time being

**Comment by stephanh** [comment]
Can you bump the patch version number please.

:+1:.

**Comment by stephanh** [comment]
Can you also add a comment to the PR or the issue about why this is needed, etc. for documentation and what is actually happening

**Comment by rowandavies** [comment]
Agreed, add a comment so it's clear why we added this.  :+1:

**Comment by vineethvarghese** [comment]
Missed the version and will add the docs too.

**Comment by vineethvarghese** [comment]
Added the explanation to the issue.

**Pull request merged**
