### PR TITLE
Get test-cluster script running again with current maestro API.

### LINKED ISSUE #392: Example scripts and directory structures are not up to date

### PR DESCRIPTION
**Pull request by dkristian**
Include example hive-site.xml in assembled jar for hive queries to run out of the box.

Fixes #392

### CODE REVIEW

**Comment by stephanh** [comment]
Not sure about bundling the hive-site with the example project. It makes very strong assumptions about how your cluster is set up. For example we don't bundle the mapred-site with the project either. We provide the ability to run example locally using the tests.

There might be more we can do to make this easier. For example have a run script that warns if it can't detect the right hive settings or prompts to provide a default hive-site.xml and add it to the classpath.

**Comment by triggerNZ** [comment]
Can you also update [[doc/code.md]] to reflect the current running instructions

**Comment by stephanh** [comment]
Closing this in favour of #423 where it is picked up again.

Thank you @dkristian!

**Comment by dkristian** [comment]
No worries, @stephanh - I was going to do the same once #423 was merged :-)

**Pull request closed without merging**
